--
CREATE TABLE COMPANYDICT
(
    ID     INT AUTO_INCREMENT PRIMARY KEY,
    TICKER VARCHAR(64)  NOT NULL UNIQUE,
    NAME   VARCHAR(250) NOT NULL UNIQUE
);
--
CREATE TABLE DIVHISTORY
(
    ID     INT AUTO_INCREMENT PRIMARY KEY,
    OPEN   DECIMAL(10, 4),
    HIGH   DECIMAL(10, 4),
    LOW    DECIMAL(10, 4),
    CLOSE  DECIMAL(10, 4),
    DIVS   DECIMAL(10, 4),
    SPLIT  DECIMAL(10, 4),
    VOLUME BIGINT,
    COMPANY_ID INT,
    CONSTRAINT FK_DIVHISTORY_COMPANYDICT FOREIGN KEY (COMPANY_ID) REFERENCES COMPANYDICT(ID)

);
